### ISSUE TITLE
remote 模块错误 TypeError: target[property] is not a function

### ISSUE THREAD

**Issue by Rensr0** [ocsjs/ocs-desktop#4]
![32cc23517d0496f6ee2c5d471ce20d14](https://github.com/ocsjs/ocs-desktop/assets/126645451/c54325c4-562c-474e-8524-9dbf049a58ca)
ubuntu 18.04 使用 ocs-2.5.2-setup-linux-x86_64.AppImage 这个版本时输入以下命令运行程序，弹出如上图所示错误，请问该如何解决？
```
$ chmod +x ocs-2.5.2-setup-linux-x86_64.AppImage 
$ ./ocs-2.5.2-setup-linux-x86_64.AppImage 
```
```
[信息] 2024/1/8 17:35:27 	 version 2.5.2
[信息] 2024/1/8 17:35:27 	 OCS服务启动成功 => 15319
[信息] 2024/1/8 17:35:27 	 初始化错误处理  耗时: 67
[信息] 2024/1/8 17:35:27 	 启动接口服务  耗时: 11
[信息] 2024/1/8 17:35:27 	 初始化本地设置  耗时: 68
[信息] 2024/1/8 17:35:27 	 初始化自动启动  耗时: 1
[信息] 2024/1/8 17:35:27 	 初始化远程通信模块  耗时: 31
[信息] 2024/1/8 17:35:27 	 注册app事件监听器  耗时: 31
[信息] 2024/1/8 17:35:28 	 启动渲染进程  耗时: 1279
[信息] 2024/1/8 17:35:28 	 OCS启动程序  耗时: 1346
[信息] 2024/1/8 17:35:28 	 render store init
[错误] 2024/1/8 17:35:28 	 未捕获的异步错误 TypeError: target[property] is not a function
```

**Comment by lei01023** [comment]
您好，其中还包含无法识别到浏览器信息，第一次登录的时候并没有识别到浏览器，但是我在通用设置里面配置好之后，仍无法识别到浏览器。
![image](https://github.com/ocsjs/ocs-desktop/assets/126645451/456f28d1-2e5e-4558-8c7d-9ea0affa2039)
![image](https://github.com/ocsjs/ocs-desktop/assets/126645451/106259d2-2b9c-42c2-81b8-9cb5cd7c733c)
![image](https://github.com/ocsjs/ocs-desktop/assets/126645451/663b80c5-abf4-47ac-9631-38384953cc8e)

**Comment by qxzg** [comment]
Archlinux 也存在同样的问题，但是手动配置Edge可执行文件路径后不影响正常使用
